#!/bin/bash

(
cat << EOF
$GC_JOB_ID $GC_PARAM $GC_DEBUG
$DATASETSPLIT $DATASETPATH $DATASETBLOCK $DATASETNICK
$MAX_EVENTS $SKIP_EVENTS
$FILE_NAMES
$TEST_HW $TEST_KEY
$MY_SETTING $PARAM_LOOKUP $VAR1 $VAR2 $B $C
$META_KEY1 $META_KEY2 $META_KEY3
EOF
) > output.vars1
export > output.vars2
export > output.vars3
